include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_relative_lib_imports
    - implementation_imports
    - require_trailing_commas
    - sort_constructors_first
    - sort_child_properties_last
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_final_fields