arb-dir: lib/app/core/l10n/templates
output-dir: lib/app/core/l10n/localizations
template-arb-file: app_pt.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
### Uncomment when generating.
# synthetic-package: false