name: site
description: Felipe Sales | Social Links.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  url_launcher: ^6.0.18
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
