name: site
description: Felipe Sales | Social Links.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  firebase_analytics: ^9.3.2
  firebase_core: ^1.21.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.4
  google_fonts: ^3.0.1
  http: ^0.13.5
  lottie: ^1.4.1
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/components/
    - assets/components/contact/
    - assets/components/experience/
    - assets/components/presentation/
    - assets/components/projects/
    - assets/components/social/
