name: site
description: Felipe Sales | Social Links.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.1.3
  firebase_core: ^2.6.1
  firebase_remote_config: ^3.0.12
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  lottie: ^2.2.0
  scrollable_positioned_list: ^0.3.5
  url_launcher: ^6.1.9
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/components/
    - assets/components/contact/
    - assets/components/experience/
    - assets/components/presentation/
    - assets/components/projects/
    - assets/components/social/
