name: site
description: Felipe Sales | Social Links.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  dart_code_metrics: ^5.6.0
  firebase_analytics: ^10.1.5
  firebase_core: ^2.7.1
  firebase_core_platform_interface: ^4.5.3
  firebase_core_web: ^2.2.2
  firebase_remote_config: ^3.0.14
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.3
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  intl: ^0.17.0
  lottie: ^2.2.0
  scrollable_positioned_list: ^0.3.5
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/components/
    - assets/components/contact/
    - assets/components/experience/
    - assets/components/presentation/
    - assets/components/projects/
    - assets/components/social/
  generate: true